-- AlterTable
ALTER TABLE `cursos` MODIFY `status_Cursos` ENUM('CONCLUIDO', 'CURSANDO', 'NAO_INFORMADO') NOT NULL;

-- AlterTable
ALTER TABLE `formacao_academica` MODIFY `nivel_formacao` ENUM('ENSINO_MEDIO', 'TECNICO', 'GRADUACAO', 'POS_GRADUACAO', 'NAO_INFORMADO') NOT NULL,
    MODIFY `status_Academico` ENUM('CONCLUIDO', 'CURSANDO', 'NAO_INFORMADO') NOT NULL;

-- AlterTable
ALTER TABLE `idiomas` MODIFY `nivel_Idioma` ENUM('BASICO', 'INTERMEDIARIO', 'AVANCADO', 'FLUENTE', 'NAO_INFORMADO') NOT NULL,
    MODIFY `nome_Idioma` ENUM('ALEMAO', 'ARABE', 'COREANO', 'ESPANHOL', 'FRANCES', 'INGLES', 'ITALIANO', 'JAPONES', 'MANDARIM', 'RUSSO', 'TAILANDES', 'NAO_INFORMADO') NOT NULL;

-- AlterTable
ALTER TABLE `perfilhistorico` MODIFY `Tipo` ENUM('DADOS_INSTRUTOR', 'PROFILE', 'FORMACAO_ACADEMICA', 'CURSO', 'COMPETENCIA', 'SOFTSKILL', 'SITUACAO_PROFISSIONAL', 'IDIOMA', 'NAO_INFORMADO') NOT NULL;

-- AlterTable
ALTER TABLE `situacao_profissional` MODIFY `nome_Setor` ENUM('ENGENHARIA', 'BDO', 'TEF', 'BD', 'RH', 'COMPRAS', 'BICO', 'CRIN', 'LOGISTICA', 'QMM', 'TOTO', 'IMPACT', 'FERRAMENTARIA', 'PRODUCAO', 'BPS', 'ETS', 'HSE', 'ESPAÇO_SAUDE', 'NAO_INFORMADO') NULL;

-- AlterTable
ALTER TABLE `soft_skills` MODIFY `nome_SoftSkills` ENUM('COMUNICACAO', 'TRABALHO_EM_EQUIPE', 'LIDERANCA', 'EMPATIA', 'PROATIVIDADE', 'RESOLUCAO_DE_PROBLEMAS', 'PENSAMENTO_CRITICO', 'GESTAO_DO_TEMPO', 'ORGANIZACAO', 'CRIATIVIDADE', 'NEGOCIACAO', 'RESILIENCIA', 'ESCUTA_ATIVA', 'RESPONSABILIDADE', 'AUTONOMIA', 'APRENDIZADO_CONTINUO', 'INOVACAO', 'ORATORIA', 'COMPROMETIMENTO', 'NAO_INFORMADO') NOT NULL;
