services:
  api:
    build:
      context: ./TalentFlow.Backend
      dockerfile: ../BackDocker
    ports: 
      - 5083:5024
    image: talentflow-api
    depends_on:
      - prisma

    environment:
      DATABASE_URL: "mysql://talentflow_admin:987abc@456def@prisma:3306/talentflow"

  prisma:
    image: mysql:8
    container_name: talentflow-db
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE      : talentflow
      MYSQL_USER          : talentflow_admin
      MYSQL_PASSWORD      : 987abc@456def
    ports: 
      - 5555:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
